modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="ya_fnafmod"
version="1.0.0"
displayName="Yet Another FNAF Mod: Extra Additions"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MarceloGToonz, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.ya_fnafmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration